title: Welcome!

author:
  name: Abdul Hafiz S Issah
  email: issahhafiz@gmail.com

description: [Hello and welcome! I'm Hafiz, a graduate student dedicated to pushing the boundaries of seismic data compression and processing efficiency. Some topics of interest include numerical analysis, Distributed Acoustic Sensing data, and fast algorithms.  Here at my personal website, I'm excited to share my journey, research projects, and insights into the fascinating world of geophysics and computational science.]

# sass:
#   quiet_deps: true

# remote_theme: jekyll/minima
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Generate social links in footer.
minima:
  skin: classic
  social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
   - { platform: github,         user_url: "https://github.com/aissah"}
   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=V2WpmiwAAAAJ&hl=en"}
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/abdul-hafiz-issah-22156b11b/" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
